### ISSUE TITLE
Add WebRTC

### ISSUE THREAD

**Issue by lurumdare** [CHEF-KOCH/Fingerprinting#2]
Sound card leaks..

**Comment by lurumdare** [comment]
@CHEF-KOCH 
https://browserleaks.com/webrtc
Media Devices

**Comment by CHEF-KOCH** [comment]
That's not the "sound card" and the reason why I added "more information requested". 

There exist:
* API specific "leaks" (not really leaks it's by RFC/protocol design) - That's what you refering too. This can be fixed by changing the RFC/protocol.
* Acustic sound fingerprinting](https://en.wikipedia.org/wiki/Acoustic_fingerprint) - This can't be fixed, the goverment uses spcial rooms to prevent exfiltration. 

WebRTC is considerable not a problem anymore, almost all browsers got an advance option to disable it via Browser settings, flags or extensions e.g. uBlock. The rest which "leaks" information can't be used anyway, these are random generated ID's which can'
t expose you - because they are not unique at all, the "has camera" & "has microphone" detection is also controlable via Linux/Windows by restriting the browser permissions directly. You also can do this per-websites only within the browser directly, click the little icon in the URL bar and change websites permission -> 0 detection. 


However WebRTC will definitly be covered.
